config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "recordings#index"
  
  get "/recordings", to: "recordings#index"
  get "/recordings/:id", to: "recordings#show", as: :show_summary

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/bbb_helper.rb
# frozen_string_literal: true

# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.

require 'bbb/credentials'
require 'bigbluebutton_api'

module BbbHelper
  extend ActiveSupport::Concern
  attr_writer :cache, :cache_enabled # Rails.cache store is assumed.  # Enabled by default.

  # Sets a BigBlueButtonApi object for interacting with the API.
  def bbb
    @bbb_credentials ||= initialize_bbb_credentials
    BigBlueButton::BigBlueButtonApi.new(@bbb_credentials.endpoint, @bbb_credentials.secret, '1.0', Rails.logger)
  rescue StandardError => e
    logger.error("Error in creating BBB object: #{e}")
  end

	# Fetches all recordings for a room.
	def recordings
		# res = Rails.cache.fetch("recordings/recordings", expires_in: 30.minutes) if Rails.configuration.cache_enabled
		
		res = bbb.get_recordings
		recordings_formatted(res)
	end

	# Fetch an individual recording
	def recording(record_id)
		r = bbb.get_recordings(recordID: record_id)
		unless r.key?(:error)

			r[:playbacks] = if !r[:playback] || !r[:playback][:format]
												[]
											elsif r[:playback][:format].is_a?(Array)
												r[:playback][:format]
											else
												[r[:playback][:format]]
											end

			r.delete(:playback)
		end

		r[:recordings][0]
	end

	def recording_date(date)
    # NOTE: if we really wanted ordinalization, then we can add an if statement to ordinalize if locale is en.
    # .ordinalize does not work with other locales
    return date.strftime("%B #{date.day}, %Y.") unless I18n.locale.eql?(:en)

    date.strftime("%B #{date.day.ordinalize}, %Y.")
  end

  # Helper for converting BigBlueButton dates into a nice length string.
  def recording_length(playbacks)
    # Stats format currently doesn't support length.
    valid_playbacks = playbacks.reject { |p| p[:type] == 'statistics' }
    return '0 min' if valid_playbacks.empty?

    len = valid_playbacks.first[:length]
    if len > 60
      "#{(len / 60).round} hrs"
    elsif len.zero?
      '< 1 min'
    else
      "#{len} min"
    end
  end
    
  private

	# Format playbacks in a more pleasant way.
	def recordings_formatted(res)
		res[:recordings].each do |r|
			next if r.key?(:error)

			r[:playbacks] = if !r[:playback] || !r[:playback][:format]
												[]
											elsif r[:playback][:format].is_a?(Array)
												r[:playback][:format]
											else
												[r[:playback][:format]]
											end

			r.delete(:playback)
		end
		res[:recordings].sort_by { |rec| rec[:endTime] }.reverse
	end

  # Emulates a builder for initializing the a newly created Bbb::Credentials object.
  def initialize_bbb_credentials
    Bbb::Credentials.new(Rails.configuration.bigbluebutton_endpoint, Rails.configuration.bigbluebutton_secret)
  end
end

app/controllers/recordings_controller.rb
require 'ML/recording_summarizer'

class RecordingsController < ApplicationController
  include BbbHelper

  def index
    begin
     @recordings = recordings
    rescue BigBlueButton::BigBlueButtonException => e
      logger.error(e.to_s)
      flash.now[:alert] = t('default.recording.server_down')
      @recordings = []
    end
  end

  # GET recordings/:record-id
  def show
    @recording = recording(params[:id])
    

    puts("\n\n**** @recording: #{@recording}")

    @summarizer = ML::RecordingSummarizer.new(@recording, Rails.configuration.openai_key)
    @recording[:summary] = @summarizer.summary
    @recording[:summaryTS] = @summarizer.summary(true)

    puts("\n\n**** @summarizer.summary(true): #{@summarizer.summary(true)}")

  end

  helper_method :recording_date, :recording_length
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recording_helper.rb
module RecordingHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hackfest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recordings/index.html.erb
<div class="m-20" >

<%= render "shared/header" %>

<%= render "shared/body" %>

<%= render "shared/footer" %>

</div>

app/views/recordings/show.html.erb
<div class="m-20" >

    <%= render "shared/header" %>

    <%= render "shared/components/summary" %>

    <%= render "shared/components/topics" %>

    <%= render "shared/footer" %>

</div>

app/views/shared/_body.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<div id="body">
 
    <div class = "flex justify-between items-center rounded-lg border mb-10">
    <table class="w-full max-w-full rounded-lg text-left border-collapse text-sm" >
      <thead class="text-left uppercase border-b rounded-lg bg-gray-100 text-sm text-gray-500 font-sans py-4" >
        <tr>
          <th class="px-6 py-4"><%= t("default.recording.table.name") + "/" + t("default.recording.table.description") %></th>
          <th class="px-6"><%= t("default.recording.table.date") %></th>
          <th class="px-6"><%= t("default.recording.table.duration") %></th>
          <th class="px-6"><%= t("default.recording.table.formats") %></th>
          <th class="px-2 "></th>  
        </tr>
      </thead>
      <tbody id="recording-table">
        <% if @recordings.empty? %>
          <tr>
            <td colspan="7" class="text-center h4 p-6 font-weight-normal">
              <%= t("default.recording.no_recordings") %>
            </td>
          </tr>
        <% else %>
          <% @recordings.each do |recording| %>
            <%= render "shared/components/recording_row", recording: recording %>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>

</div>

app/views/shared/_footer.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<div id="footer">
      <div class="navbar fixed-bottom">
        <div class="text-center">
          <p class="">Blindside Networks Hackfest '23 | Mariam & Shamiso</p>
        </div>
      </div>
    </div>

app/views/shared/_header.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>

<div id="header">
</div>

app/views/shared/components/_recording_row.html.erb
<%
# BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.
# Copyright (c) 2018 BigBlueButton Inc. and by respective authors (see below).
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free Software
# Foundation; either version 3.0 of the License, or (at your option) any later
# version.
#
# BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License along
# with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
%>
<tr class="border-b text-left ">
  <td class="p-0">
    <div class="text-left font-sans px-5 py-3 ">
      <div id="recording-title" class="form-inline font-bold edit_hover_class" >
          <% if recording[:metadata][:name] %>
            <%= link_to recording[:metadata][:name], show_summary_path(recording[:recordID]), :name => recording[:metadata][:name], id: 'recording-title-text', class: "text-wrap text-blue-700 input recording-text", target: "_blank"%>
          <% else %>
            <%= link_to recording[:name], show_summary_path(recording[:recordID]), :name => recording[:name], id: 'recording-title-text', class: "text-wrap input text-blue-700 recording-text",target: "_blank" %>
          <% end %>
    
      </div>
      <div id="recording-description" class="form-inline edit_hover_class" 
           data-recordid="<%= recording[:recordID] %>" 
           data-launch-nonce="<%= @launch_nonce %>"
        <text id='recording-description-text' class="text-wrap recording-text"><%= recording[:metadata][:description] %></text>
          
      </div>
    </div>
  </td>

  <td class="p-0 text-left font-sans px-6 py-3">
    <%= recording_date(recording[:startTime]) %>
  </td>

  <td class="p-0 text-left font-sans px-6 py-3">
    <%= recording_length(recording[:playbacks]) %>
  </td>

  <td class="p-0 text-left px-6 py-2" style='white-space: nowrap'>
    <div class="flex items-end ">
        <% sorted_playbacks = recording[:playbacks].sort_by { |hsh| hsh[:type] }%>
        <% sorted_playbacks.each do |p| %>
          <% if p[:type] == 'presentation' %>
            <%= link_to p[:url], :'data-toggle' => 'tooltip' , title: p[:type], target: "_blank", class: "mr-4 hover:bg-white hover:text-blue-700" do %>
              <div class="bg-gray-200 p-2 rounded hover:bg-gray-300">
                <div class= "bg-bbb-blue rounded-full" >
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 bg-bbb-blue text-blue-600 m-2" fill="none" viewBox="0 0 22 22" stroke="currentColor" stroke-width="2">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
                    </svg>
                </div>
              </div>  
            <% end %>
          <% elsif p[:type] == 'statistics' %>
            <%= link_to p[:url], :'data-toggle' => 'tooltip' , title: p[:type], target: "_blank" , class: "mr-4 hover:bg-white hover:text-blue-700 " do %>
              <div class="bg-gray-200 p-2 rounded hover:bg-gray-300">
                <div class= "bg-bbb-blue rounded-full">
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 bg-bbb-blue text-blue-600 m-2 " fill="none" viewBox="0 0 22 22" stroke="currentColor" stroke-width="2">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M11 3.055A9.001 9.001 0 1020.945 13H11V3.055z" />
                    <path stroke-linecap="round" stroke-linejoin="round" d="M20.488 9H15V3.512A9.025 9.025 0 0120.488 9z" />
                  </svg>
                </div>
              </div>
            <% end %>
          <% elsif p[:type] == 'video' %>
            <%= link_to p[:url], :'data-toggle' => 'tooltip' , title: p[:type],  target: "_blank", class: "mr-4 hover:bg-white hover:text-blue-700" do %>
              <div class="bg-gray-200 p-2 rounded hover:bg-gray-300">
                <div class= "bg-bbb-blue rounded-full">
                  <svg xmlns="http://www.w3.org/2000/svg"  class="h-5 w-5 bg-bbb-blue text-blue-600 m-2 " fill="none" viewBox="0 0 22 22" stroke="currentColor" stroke-width="2">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M14.752 11.168l-3.197-2.132A1 1 0 0010 9.87v4.263a1 1 0 001.555.832l3.197-2.132a1 1 0 000-1.664z" />
                    <path stroke-linecap="round" stroke-linejoin="round" d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                </div>
              </div>
            <% end %> 
          <% else # other format %> 
            <%= link_to p[:url], :'data-toggle' => 'tooltip' , title: p[:type],  target: "_blank", class: "mr-4 hover:bg-white hover:text-blue-700" do %>
              <div class="bg-gray-200 p-2 rounded hover:bg-gray-300">
                <div class= "text-blue-600 rounded-full">
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 bg-bbb-blue text-blue-600 m-2" fill="none" viewBox="0 0 22 22" stroke-width="1.5" stroke="currentColor" >
                    <path stroke-linecap="round" stroke-linejoin="round" d="M13.19 8.688a4.5 4.5 0 011.242 7.244l-4.5 4.5a4.5 4.5 0 01-6.364-6.364l1.757-1.757m13.35-.622l1.757-1.757a4.5 4.5 0 00-6.364-6.364l-4.5 4.5a4.5 4.5 0 001.242 7.244" />
                  </svg>
                </div>
              </div>
            <% end %>
          <% end %>
      <% end %> <%# end of sorted playbacks %>
    </div>
  </td>
    
  <td class="p-0 text-left mx-6 mr-2 px-2 my-4">
    <div class="item-action dropdown place-items-center items-center">
      <% dropdown_id = "dropdown#{recording[:recordID]}"%>
      <a href="javascript:void(0)" id="dropdownDefault" type="button"  data-dropdown-toggle=<%="dropdown#{recording[:recordID]}"%> class="bg-white no-underline text-gray-700 hover:text-blue-700 hover:bg-white">
        <%# vertical elipses icon %>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 5v.01M12 12v.01M12 19v.01M12 6a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2z" />
        </svg>
      </a>        
      <div aria-labelledby="dropdownDefault" id=<%="dropdown#{recording[:recordID]}"%> class="hidden dropdown-content dropdown-menu dropdown-menu-right w-52" aria-labelledby="dropdownDefault">
      </div>      
        
    </div>
  </td>
</tr>

app/views/shared/components/_summary.html.erb
    <div class="text-4xl text-blue-700"> 
        <%= "Summary of #{@recording[:metadata][:name] || @recording[:name]}" %>
    </div>

    <hr>
    
    <div class="text-xl m-2"> 
       <%= "#{@recording[:summary]}" %>
    </div>

app/views/shared/components/_topics.html.erb
<div class="text-4xl text-blue-700 mt-6"> 
   <%= "Main Topics" %>
</div>

<hr>

<div class="text-xl m-2"> 
   <%= "#{@recording[:summaryTS]}" %>
</div>